import test from 'node:test';
import assert from 'node:assert/strict';
import { createTriggerIntent, executeTrigger, reconcileTrigger, rejectResponseAuthority, triggerBytes, validateTriggerAuthority } from '../src/browser-relay/browser-relay.js';
import { createConversationRegistration, createGenerationAuthority, createRelayControlRecord, createRelayControlState, registrationPaths, resolveArchitectSession, validateConversationRegistration, validateGenerationAuthority, validateRelayControlRecord, validateRelayControlState } from '../src/browser-relay/registration.js';

const base = (overrides = {}) => ({
  terminalPublication: { publicationId: 'GH-PUB-' + 'a'.repeat(32), missionId: 'MISSION-X', parentMessageId: 'MSG-0', messageId: 'MSG-1', workerOutcome: 'PASS', resultAddress: 'architect' },
  expectedMission: 'MISSION-X', expectedLineage: { parentMessageId: 'MSG-0', messageId: 'MSG-1' },
  architectGeneration: 'GEN-1', conversation: { unique: true, id: 'CONV-1' }, composerCount: 1,
  relayPort: 9333, dedicatedSession: true, preSendUserMessageBoundary: { messageId: 'USER-1', messageCount: 4 }, triggerId: 'TRIGGER-1', ...overrides
});

test('trigger bytes and hash are exact and deterministic', () => { const a = triggerBytes(); const b = triggerBytes(); assert.deepEqual(a, b); assert.equal(a.text, 'verify & next'); assert.equal(a.byteLength, 13); });
test('only the exact wake-up text is used', () => { const x = createTriggerIntent(base()); assert.equal(x.intent.triggerText, 'verify & next'); assert.match(x.intent.triggerSha256, /^[0-9a-f]{64}$/); });
test('terminal publication is required before eligibility', () => { const x = validateTriggerAuthority({...base(), terminalPublication: null}); assert.equal(x.classification, 'FAIL_CLOSED'); assert.equal(x.sendCount, 0); });
test('mission and lineage mismatches fail closed', () => { assert.equal(validateTriggerAuthority(base({ expectedMission: 'OTHER' })).classification, 'FAIL_CLOSED'); assert.equal(validateTriggerAuthority(base({ expectedLineage: { parentMessageId: 'OTHER', messageId: 'MSG-1' } })).classification, 'FAIL_CLOSED'); });
test('consumed and duplicate trigger gates suppress send', () => { assert.equal(validateTriggerAuthority(base({ consumed: true })).classification, 'TRIGGER_REFUSED'); assert.equal(validateTriggerAuthority(base({ priorSuccessfulTrigger: true })).classification, 'TRIGGER_REFUSED'); });
test('pause, stop, abort, reconciliation, and circuit gates suppress send', () => { for (const controlState of ['PAUSED_BY_RONY', 'STOP', 'ABORT_CURRENT_WORKER', 'RECONCILIATION_REQUIRED', 'CIRCUIT_OPEN']) assert.equal(validateTriggerAuthority(base({ controlState })).classification, 'TRIGGER_REFUSED'); });
test('generation, conversation, and composer gates are strict', () => { assert.equal(validateTriggerAuthority(base({ architectGeneration: '' })).classification, 'FAIL_CLOSED'); assert.equal(validateTriggerAuthority(base({ conversation: { unique: false, id: 'CONV-1' } })).classification, 'FAIL_CLOSED'); assert.equal(validateTriggerAuthority(base({ composerCount: 0 })).classification, 'FAIL_CLOSED'); assert.equal(validateTriggerAuthority(base({ composerCount: 2 })).classification, 'FAIL_CLOSED'); });
test('relay session and port boundaries reject shared or forbidden ports', () => { assert.equal(validateTriggerAuthority(base({ dedicatedSession: false })).classification, 'FAIL_CLOSED'); assert.equal(validateTriggerAuthority(base({ relayPort: 9222 })).classification, 'FAIL_CLOSED'); assert.equal(validateTriggerAuthority(base({ relayPort: 9223 })).classification, 'FAIL_CLOSED'); assert.equal(validateTriggerAuthority(base({ relayPort: 9333 })).classification, 'ELIGIBLE'); });
test('intent binds reviewed publication, generation, conversation, and pre-send boundary', () => { const x = createTriggerIntent(base()); assert.equal(x.intent.reviewedPublicationId, base().terminalPublication.publicationId); assert.equal(x.intent.architectGeneration, 'GEN-1'); assert.equal(x.intent.conversationId, 'CONV-1'); assert.equal(x.intent.preSendUserMessageBoundary.messageId, 'USER-1'); });
test('intent is durable before send and exactly one send occurs', async () => { const events=[]; const x=await executeTrigger(base(), {persistIntent:async i=>events.push(['intent',i]),rediscover:async()=>({generation:'GEN-1',conversationId:'CONV-1',composerCount:1}),send:async text=>{events.push(['send',text]);return {sent:true}},persistResult:async r=>events.push(['result',r]),disconnect:async()=>events.push(['disconnect'])}); assert.equal(x.classification,'SENT'); assert.equal(x.sendCount,1); assert.deepEqual(events.map(e=>e[0]),['intent','send','result','disconnect']); });
test('reverification failure prevents send', async () => { let sends=0; const x=await executeTrigger(base(), {persistIntent:async()=>{},rediscover:async()=>({generation:'GEN-2',conversationId:'CONV-1',composerCount:1}),send:async()=>{sends++;return {sent:true}},persistResult:async()=>{},disconnect:async()=>{}}); assert.equal(x.classification,'FAIL_CLOSED'); assert.equal(sends,0); });
test('ambiguous acknowledgement reconciles sent without retry', async () => { let sends=0; const x=await executeTrigger(base(), {persistIntent:async()=>{},rediscover:async()=>({generation:'GEN-1',conversationId:'CONV-1',composerCount:1}),send:async()=>{sends++;return {acknowledgement:'AMBIGUOUS',observation:'SENT',currentUserMessageBoundary:{messageId:'USER-1',messageCount:5,lastUserText:'verify & next'}}},persistResult:async()=>{throw new Error('must not synthesize result')},disconnect:async()=>{}}); assert.equal(x.classification,'RECONCILED_SENT'); assert.equal(x.sendCount,0); assert.equal(sends,1); });
test('ambiguous absence is proven without retry', () => { const x=reconcileTrigger({intent:createTriggerIntent(base()).intent,observation:'PROVEN_NOT_SENT'}); assert.equal(x.classification,'PROVEN_NOT_SENT'); assert.equal(x.sendCount,0); });
test('unknown ambiguity requires reconciliation', () => { const x=reconcileTrigger({intent:createTriggerIntent(base()).intent,observation:'UNKNOWN'}); assert.equal(x.classification,'RECONCILIATION_REQUIRED'); assert.equal(x.sendCount,0); });
test('invalid observation and invalid intent fail closed', () => { assert.equal(reconcileTrigger({intent:createTriggerIntent(base()).intent,observation:'ACCEPTED'}).classification,'FAIL_CLOSED'); assert.equal(reconcileTrigger({intent:null,observation:'UNKNOWN'}).classification,'FAIL_CLOSED'); });
test('refused send is recorded and disconnects', async () => { let result, disconnected=false; const x=await executeTrigger(base(), {persistIntent:async()=>{},rediscover:async()=>({generation:'GEN-1',conversationId:'CONV-1',composerCount:1}),send:async()=>({sent:false}),persistResult:async r=>{result=r},disconnect:async()=>{disconnected=true}}); assert.equal(x.resultState,'TRIGGER_REFUSED'); assert.equal(result.resultState,'TRIGGER_REFUSED'); assert.equal(disconnected,true); });
test('assistant response text cannot become workflow authority', () => { const x=rejectResponseAuthority('ACCEPTED; dispatch curator'); assert.equal(x.classification,'FAIL_CLOSED'); assert.equal(x.ignored,true); });
test('Prompt Ledger issue text is outside the trigger API', () => { const x=createTriggerIntent(base()); assert.equal(x.intent.triggerText,'verify & next'); assert.equal(x.intent.triggerText.includes('dispatch curator'),false); });
test('dynamic rediscovery is required rather than stale target IDs', async () => { let discovered=0; const x=await executeTrigger(base(), {persistIntent:async()=>{},rediscover:async()=>{discovered++;return {generation:'GEN-1',conversationId:'CONV-1',composerCount:1}},send:async()=>({sent:true}),persistResult:async()=>{},disconnect:async()=>{}}); assert.equal(x.classification,'SENT'); assert.equal(discovered,1); });
test('reconciliation send count remains zero after crash boundary', () => { const intent=createTriggerIntent(base()).intent; const x=reconcileTrigger({intent,observation:'SENT',currentUserMessageBoundary:{messageId:'OTHER',messageCount:5,lastUserText:'verify & next'}}); assert.equal(x.classification,'RECONCILIATION_REQUIRED'); assert.equal(x.sendCount,0); });

const registrationFixture = (overrides = {}) => {
  const authority = createGenerationAuthority({ authorityId: 'AUTH-001', missionId: 'MISSION-X', generation: 'GEN-1', createdAt: 100, architectDecisionId: 'DEC-001', ...overrides.authority });
  const registration = createConversationRegistration({ registrationId: 'REG-001', authorityId: authority.authorityId, authoritySha256: authority.authoritySha256, missionId: authority.missionId, generation: authority.generation, conversationId: '6a7f0e19-6e20-83ec-b052-c62f0e926242', conversationUrl: 'https://chatgpt.com/c/6a7f0e19-6e20-83ec-b052-c62f0e926242', createdAt: 101, ...overrides.registration });
  const control = createRelayControlState({ controlId: 'CTRL-001', updatedAt: 102, state: overrides.controlState ?? 'ACTIVE' });
  return { authority, registration, control, authorityPointer: { pointerKind: 'ARCHITECT_SESSION_AUTHORITY', pointerState: 'CURRENT', recordId: authority.authorityId, recordSha256: authority.authoritySha256 }, registrationPointer: { pointerKind: 'ARCHITECT_SESSION_REGISTRATION', pointerState: 'CURRENT', recordId: registration.registrationId, recordSha256: registration.registrationSha256 }, observedSession: { conversationId: registration.conversationId, conversationUrl: registration.conversationUrl, composerCount: 1, relayPort: 9333 } };
};

test('generation authority and registration use deterministic integrity hashes', () => { const a = registrationFixture(); assert.equal(validateGenerationAuthority(a.authority).valid, true); assert.equal(validateConversationRegistration(a.registration).valid, true); assert.equal(validateRelayControlState(a.control).valid, true); assert.deepEqual(registrationPaths({ authorityId: 'AUTH-001', registrationId: 'REG-001' }), { authorityPath: 'evidence/architect-sessions/authorities/AUTH-001.json', registrationPath: 'evidence/architect-sessions/registrations/REG-001.json', authorityPointer: 'evidence/current/LATEST_ARCHITECT_SESSION_AUTHORITY.json', registrationPointer: 'evidence/current/LATEST_ARCHITECT_SESSION_REGISTRATION.json', controlPointer: 'evidence/current/RELAY_CONTROL.json' }); });
test('immutable relay-control record has deterministic path, schema, and hash', () => { const c = createRelayControlRecord({ recordId: 'RELAY-CONTROL-001', missionId: 'MISSION-X', relayPort: 9333, state: 'ACTIVE', createdAt: 103, createdByRole: 'architect' }); assert.equal(validateRelayControlRecord(c).valid, true); assert.deepEqual(registrationPaths({ authorityId: 'AUTH-001', registrationId: 'REG-001', controlId: c.recordId }).controlPath, 'evidence/architect-sessions/controls/RELAY-CONTROL-001.json'); assert.equal(c.controlSha256.length, 64); });
test('immutable ACTIVE relay-control pointer resolves without send authority', () => { const x = registrationFixture(); x.controlRecord = createRelayControlRecord({ recordId: 'RELAY-CONTROL-001', missionId: 'MISSION-X', relayPort: 9333, state: 'ACTIVE', createdAt: 103, createdByRole: 'architect' }); x.controlPointer = { pointerKind: 'RELAY_CONTROL', pointerState: 'CURRENT', recordId: x.controlRecord.recordId, recordSha256: x.controlRecord.controlSha256 }; const resolved = resolveArchitectSession(x); assert.equal(resolved.registrationReady, true); assert.equal(resolved.sendAuthorized, false); });
test('immutable relay-control defects fail closed', () => { const x = registrationFixture(); x.controlRecord = createRelayControlRecord({ recordId: 'RELAY-CONTROL-001', missionId: 'MISSION-X', relayPort: 9333, state: 'ACTIVE', createdAt: 103, createdByRole: 'architect' }); x.controlPointer = { pointerKind: 'RELAY_CONTROL', pointerState: 'CURRENT', recordId: x.controlRecord.recordId, recordSha256: '0'.repeat(64) }; assert.equal(resolveArchitectSession(x).classification, 'FAIL_CLOSED'); const y = registrationFixture(); y.controlRecord = createRelayControlRecord({ recordId: 'RELAY-CONTROL-001', missionId: 'MISSION-X', relayPort: 9333, state: 'ACTIVE', createdAt: 103, createdByRole: 'architect' }); y.controlPointer = { pointerKind: 'RELAY_CONTROL', pointerState: 'CURRENT', recordId: 'OTHER', recordSha256: y.controlRecord.controlSha256 }; assert.equal(resolveArchitectSession(y).classification, 'FAIL_CLOSED'); });
test('immutable relay-control mission, port, unknown state, lineage, and suppressing states fail closed', () => { const wrongMission = registrationFixture(); wrongMission.controlRecord = createRelayControlRecord({ recordId: 'RELAY-CONTROL-001', missionId: 'OTHER', relayPort: 9333, state: 'ACTIVE', createdAt: 103, createdByRole: 'architect' }); wrongMission.controlPointer = { pointerKind: 'RELAY_CONTROL', pointerState: 'CURRENT', recordId: wrongMission.controlRecord.recordId, recordSha256: wrongMission.controlRecord.controlSha256 }; assert.equal(resolveArchitectSession(wrongMission).classification, 'FAIL_CLOSED'); const wrongPort = registrationFixture(); wrongPort.controlRecord = createRelayControlRecord({ recordId: 'RELAY-CONTROL-001', missionId: 'MISSION-X', relayPort: 9334, state: 'ACTIVE', createdAt: 103, createdByRole: 'architect' }); wrongPort.controlPointer = { pointerKind: 'RELAY_CONTROL', pointerState: 'CURRENT', recordId: wrongPort.controlRecord.recordId, recordSha256: wrongPort.controlRecord.controlSha256 }; assert.equal(resolveArchitectSession(wrongPort).classification, 'FAIL_CLOSED'); for (const override of [{ state: 'UNKNOWN' }, { supersedesRecordId: 42 }]) { const c = createRelayControlRecord({ recordId: 'RELAY-CONTROL-001', missionId: 'MISSION-X', relayPort: 9333, state: 'ACTIVE', createdAt: 103, createdByRole: 'architect', ...override }); assert.equal(validateRelayControlRecord(c).valid, false); } for (const state of ['PAUSED_BY_RONY', 'STOP', 'ABORT_CURRENT_WORKER', 'RECONCILIATION_REQUIRED', 'CIRCUIT_OPEN']) { const x = registrationFixture(); x.controlRecord = createRelayControlRecord({ recordId: 'RELAY-CONTROL-001', missionId: 'MISSION-X', relayPort: 9333, state, createdAt: 103, createdByRole: 'architect' }); x.controlPointer = { pointerKind: 'RELAY_CONTROL', pointerState: 'CURRENT', recordId: x.controlRecord.recordId, recordSha256: x.controlRecord.controlSha256 }; assert.equal(resolveArchitectSession(x).classification, state); assert.equal(resolveArchitectSession(x).sendAuthorized, false); } });
test('valid immutable authority and conversation binding resolve without send authority', () => { const x=resolveArchitectSession(registrationFixture()); assert.equal(x.registrationReady,true); assert.equal(x.sendAuthorized,false); assert.equal(x.architectGeneration,'GEN-1'); });
test('missing generation authority fails closed', () => { const x=registrationFixture(); delete x.authority; assert.equal(resolveArchitectSession(x).classification,'FAIL_CLOSED'); });
test('registration hash and authority reference tampering fail closed', () => { const x=registrationFixture(); x.registration.authoritySha256='0'.repeat(64); assert.equal(resolveArchitectSession(x).classification,'FAIL_CLOSED'); const y=registrationFixture(); y.registration.registrationSha256='0'.repeat(64); assert.equal(validateConversationRegistration(y.registration).valid,false); });
test('conversation identity and URL must exactly match observed session', () => { const x=registrationFixture(); x.observedSession.conversationId='OTHER'; assert.equal(resolveArchitectSession(x).classification,'FAIL_CLOSED'); const y=registrationFixture(); y.observedSession.conversationUrl='https://chatgpt.com/c/other'; assert.equal(resolveArchitectSession(y).classification,'FAIL_CLOSED'); });
test('stale, superseded, or consumed registrations cannot resolve', () => { const x=registrationFixture({ authority: { state: 'SUPERSEDED' } }); assert.equal(resolveArchitectSession(x).classification,'STALE_REGISTRATION'); const y=registrationFixture({ registration: { consumed: true } }); assert.equal(resolveArchitectSession(y).classification,'STALE_REGISTRATION'); });
test('missing or mismatched current pointers fail closed', () => { const x=registrationFixture(); x.registrationPointer.recordSha256='0'.repeat(64); assert.equal(resolveArchitectSession(x).classification,'FAIL_CLOSED'); const y=registrationFixture(); y.authorityPointer.recordId='OTHER'; assert.equal(resolveArchitectSession(y).classification,'FAIL_CLOSED'); });
test('all suppressing controls prevent registration use', () => { for (const state of ['PAUSED_BY_RONY','STOP','ABORT_CURRENT_WORKER','RECONCILIATION_REQUIRED','CIRCUIT_OPEN']) { const x=registrationFixture({ controlState: state }); assert.equal(resolveArchitectSession(x).classification,state); assert.equal(x.control.state,state); } });
test('explicit ACTIVE control is the only clear state', () => { const x=registrationFixture({ controlState: 'ACTIVE' }); assert.equal(resolveArchitectSession(x).registrationReady,true); assert.equal(x.control.state,'ACTIVE'); });
test('registration readiness cannot itself authorize a trigger or send', () => { const x=resolveArchitectSession(registrationFixture()); assert.equal(x.sendAuthorized,false); assert.equal(x.registrationReady,true); });
test('registration rejects forbidden relay ports', () => { const x=registrationFixture({ registration: { relayPort: 9222 } }); assert.equal(resolveArchitectSession(x).classification,'FAIL_CLOSED'); });
test('registration does not consume or parse assistant response text', () => { const x=resolveArchitectSession(registrationFixture()); assert.equal('assistant response text' in x,false); assert.equal(x.sendAuthorized,false); });
test('supersession requires a durable new authority rather than mutation', () => { const x=registrationFixture(); const next=createGenerationAuthority({ authorityId:'AUTH-002', missionId:'MISSION-X', generation:'GEN-2', createdAt:200, architectDecisionId:'DEC-002', supersedesAuthorityId:x.authority.authorityId }); assert.equal(validateGenerationAuthority(next).valid,true); assert.equal(x.authority.state,'ACTIVE'); });
