import test from 'node:test';
import assert from 'node:assert/strict';
import { DOCUMENTATION_TARGETS, renderDocumentationProjection } from '../src/curator/curator-document-renderer.js';
import { curatorProjection } from '../src/curator/curator-projection.js';

const events = Array.from({ length: 15 }, (_, index) => ({ sequence: index + 1, eventId: `EVT-${String(index + 1).padStart(6, '0')}`, eventType: index === 4 ? 'ARCHITECT_DECISION' : 'PROJECT_EVENT', detailsRef: `evidence/events/EVT-${String(index + 1).padStart(6, '0')}.json` }));
const input = () => ({ projectId: 'affotech-agent-orchestrator', sourceRef: 'fed93e71ec117121374a0f26e72be63143ffa792', eventRange: { first: 1, last: 15 }, events, targets: [...DOCUMENTATION_TARGETS], acceptedSource: { publicationId: 'GH-PUB-065-PROJECT-MEMORY-LIVE-EVENT-CUTOVER-REPAIR-000001', files: 95, fullTests: '693/0/0', manifestSha256: 'a'.repeat(64), archiveSha256: 'b'.repeat(64), archiveSize: 113406 }, semantic: { orch000063: 'BLOCKED', orch000064: 'ACCEPTED_ROOT_CAUSE_NOT_SOURCE', orch000065: 'CURRENT_ACCEPTED_SOURCE', orch000066: 'ACCEPTED_RECOVERY', cursor: 'NOT_CONSUMED' }, causalChains: [{ label: 'A. Initial bootstrap', sequences: [1, 2, 3], summary: 'Initial live cutover bootstrap.' }, { label: 'B. Blocked path', sequences: [4, 5], summary: 'Blocked historical path.' }, { label: 'C. Root cause', sequences: [6, 7, 8], summary: 'Accepted diagnosis.' }, { label: 'D. Repair', sequences: [9, 10, 11, 12], summary: 'Accepted repair and source.' }, { label: 'E. Recovery', sequences: [13, 14, 15], summary: 'Accepted recovery.' }], decisionClassifications: { 1: 'bootstrap', 5: 'BLOCKED', 8: 'ACCEPTED', 11: 'ACCEPTED', 15: 'ACCEPTED' } });

test('renders exactly five bound documentation targets', () => { const out = renderDocumentationProjection(input()); assert.equal(out.valid, true); assert.deepEqual(out.documentPaths, DOCUMENTATION_TARGETS); assert.equal(Object.keys(out.documents).length, 5); });
test('identical structured inputs render byte-identical documents and digest', () => { const a = renderDocumentationProjection(input()); const b = renderDocumentationProjection(input()); assert.deepEqual(Object.fromEntries(Object.entries(a.documents).map(([k, v]) => [k, v.sha256])), Object.fromEntries(Object.entries(b.documents).map(([k, v]) => [k, v.sha256]))); assert.equal(a.projectionDigest, b.projectionDigest); assert.deepEqual(a.documents, b.documents); });
test('output ordering and newline contract are deterministic', () => { const out = renderDocumentationProjection(input()); assert.deepEqual(out.documentPaths, ['docs/CURRENT_STATE.md', 'docs/PROJECT_HISTORY.md', 'docs/DECISIONS.md', 'docs/BUGS_AND_LESSONS.md', 'docs/ARCHITECTURE.md']); for (const document of Object.values(out.documents)) { assert.equal(document.content.includes('\r'), false); assert.equal(document.content.endsWith('\n'), true); assert.equal(document.content.endsWith('\n\n'), false); } });
test('content preserves accepted semantics and provenance', () => { const out = renderDocumentationProjection(input()); assert.match(out.documents['docs/CURRENT_STATE.md'].content, /GH-PUB-065/); assert.match(out.documents['docs/CURRENT_STATE.md'].content, /ORCH-000066/); assert.match(out.documents['docs/PROJECT_HISTORY.md'].content, /Blocked path/); assert.match(out.documents['docs/DECISIONS.md'].content, /BLOCKED/); assert.match(out.documents['docs/BUGS_AND_LESSONS.md'].content, /self-hash/); assert.match(out.documents['docs/ARCHITECTURE.md'].content, /on-demand/); });
test('missing required truth fails closed and cursor remains a proposal only', () => { const x = input(); delete x.acceptedSource; assert.equal(renderDocumentationProjection(x).classification, 'CURATOR_DOCUMENT_RENDERER_INVALID'); const out = renderDocumentationProjection(input()); assert.equal(out.cursorAdvanceAuthorized, false); assert.equal(out.mutationAuthorized, false); });
test('renderer and integrated Curator boundary expose the same pure API', () => { assert.equal(curatorProjection.renderDocumentationProjection, renderDocumentationProjection); });
const acceptedSourceOverlay = { decisionId: 'GH-DEC-0716f23a4d8c9e5b107a34f6c2d81e90', classification: 'ACCEPTED', acceptedSourcePublicationId: 'GH-PUB-071-PROJECT-MEMORY-CURATOR-DOCUMENT-RENDERER-REPAIR-000001', semanticFactType: 'ACCEPTED_SOURCE_BASELINE', value: { publicationId: 'GH-PUB-071-PROJECT-MEMORY-CURATOR-DOCUMENT-RENDERER-REPAIR-000001', files: 97, fullTests: '700/0/0', manifestSha256: 'c'.repeat(64), archiveSha256: 'd'.repeat(64), archiveSize: 116913 }, evidenceRefs: ['evidence/decisions/architect/GH-DEC-0716f23a4d8c9e5b107a34f6c2d81e90/decision.json'], mirroredThroughSequence: 15, overlayNotYetMirroredIntoEventLedger: true };
test('accepted current-truth overlay supersedes frozen source only in CURRENT_STATE', () => { const out = renderDocumentationProjection({ ...input(), currentTruthOverlay: [acceptedSourceOverlay] }); const current = out.documents['docs/CURRENT_STATE.md'].content; assert.match(current, /GH-PUB-071/); assert.match(current, /97 files/); assert.match(current, /700\/0\/0/); assert.match(current, /not yet mirrored/); assert.match(out.documents['docs/PROJECT_HISTORY.md'].content, /Post-ledger overlay/); });
test('non-accepted and contradictory overlays fail closed', () => { const denied = { ...acceptedSourceOverlay, classification: 'BLOCKED' }; assert.equal(renderDocumentationProjection({ ...input(), currentTruthOverlay: [denied] }).reasonCodes[0], 'CURRENT_TRUTH_OVERLAY_AUTHORITY_INVALID'); const other = { ...acceptedSourceOverlay, value: { ...acceptedSourceOverlay.value, files: 98 } }; assert.equal(renderDocumentationProjection({ ...input(), currentTruthOverlay: [acceptedSourceOverlay, other] }).reasonCodes[0], 'CURRENT_TRUTH_OVERLAY_CONTRADICTION'); });
test('overlay duplicates and multiple fact types are deterministic', () => { const renderer = { ...acceptedSourceOverlay, semanticFactType: 'CURATOR_RENDERER_ACCEPTED', value: { status: 'accepted' } }; const x = renderDocumentationProjection({ ...input(), currentTruthOverlay: [renderer, acceptedSourceOverlay, acceptedSourceOverlay] }); const y = renderDocumentationProjection({ ...input(), currentTruthOverlay: [acceptedSourceOverlay, renderer] }); assert.equal(x.projectionDigest, y.projectionDigest); });
const variableInput = (first=1,last=51, extra={}) => ({ ...input(), sourceRef:'canonical-51', eventRange:{first,last}, events:Array.from({length:last-first+1},(_,i)=>({ sequence:first+i, eventId:`CANONICAL-${first+i}`, eventType:[1,5,8,11,15,18,21,24,27,30,34,37,41,44,47,50].includes(first+i)?'ARCHITECT_DECISION':'EXECUTOR_CHECKPOINT', projectId:'affotech-agent-orchestrator', previousEventId:i?`CANONICAL-${first+i-1}`:null, detailsRef:`evidence/events/CANONICAL-${first+i}.json`, producerEventKey:`DECISION-${first+i}` })), acceptedSource:{ publicationId:'GH-PUB-077-PERSISTENT-HOST-LINEAGE-SELECTION-REPAIR-000001', files:97, fullTests:'726/0/0', manifestSha256:'e'.repeat(64), archiveSha256:'f'.repeat(64), archiveSize:119068 }, semantic:{cursor:'NOT_CONSUMED'}, semanticProfile:{currentState:{acceptedSource:{messageId:'ORCH-000077',publicationId:'GH-PUB-077',files:97,fullTests:'726/0/0',manifestSha256:'e'.repeat(64),archiveSha256:'f'.repeat(64),archiveSize:119068},lineageFoundation:{messageId:'ORCH-000077'},blockedCatchup:{messageId:'ORCH-000078',classification:'BLOCKED',eventRange:'16-51'},rendererRepair:{messageId:'ORCH-000079',classification:'ACCEPTED'},liveHost:{status:'NOT SUCCEEDED'},affotech:{status:'PROTECTED/SEPARATE'}},lessons:['variable-range repair'],architecture:['variable coherent ranges']}, causalChains:[], decisionHistory:[1,5,8,11,15,18,21,24,27,30,34,37,41,44,47,50].map(sequence=>({sequence,decisionId:`DECISION-${sequence}`,classification:'ACCEPTED',evidenceRefs:[`evidence/decisions/${sequence}.json`]})), ...extra });
test('accepts coherent canonical range 1-51 and emits exactly five docs', () => { const out=renderDocumentationProjection(variableInput()); assert.equal(out.valid,true); assert.equal(out.eventRange.last,51); assert.deepEqual(out.documentPaths,DOCUMENTATION_TARGETS); });
test('preserves backward-compatible coherent range 1-15', () => { const out=renderDocumentationProjection(variableInput(1,15)); assert.equal(out.valid,true); });
test('accepts another non-15 coherent range without fixed-final-sequence assumption', () => { const out=renderDocumentationProjection(variableInput(20,22)); assert.equal(out.valid,true); assert.match(out.documents['docs/ARCHITECTURE.md'].content,/22/); });
test('rejects range length gap duplicate reorder project and chain mismatch fail-closed', () => { assert.equal(renderDocumentationProjection({...variableInput(),events:variableInput().events.slice(0,50)}).reasonCodes[0],'EVENT_RANGE_LENGTH_INVALID'); const gap=variableInput(); gap.events[10].sequence=12; assert.equal(renderDocumentationProjection(gap).reasonCodes[0],'EVENT_PROVENANCE_INVALID'); const wrong=variableInput(); wrong.events[2].projectId='other'; assert.equal(renderDocumentationProjection(wrong).reasonCodes[0],'EVENT_PROJECT_MISMATCH'); const chain=variableInput(); chain.events[2].previousEventId='BROKEN'; assert.equal(renderDocumentationProjection(chain).reasonCodes[0],'EVENT_CHAIN_MISMATCH'); });
test('two identical 1-51 structured inputs render byte-identically with identical digests', () => { const a=renderDocumentationProjection(variableInput()); const b=renderDocumentationProjection(variableInput()); assert.deepEqual(a.documents,b.documents); assert.equal(a.projectionDigest,b.projectionDigest); });
test('current accepted source derives from structured Architect facts', () => { const x=variableInput(); x.acceptedSource={publicationId:'CURRENT-SOURCE',files:123,fullTests:'999/0/0',manifestSha256:'1'.repeat(64),archiveSha256:'2'.repeat(64),archiveSize:7}; const out=renderDocumentationProjection(x); assert.match(out.documents['docs/CURRENT_STATE.md'].content,/CURRENT-SOURCE/); assert.match(out.documents['docs/CURRENT_STATE.md'].content,/123 files/); });
test('arbitrary later Architect BLOCKED INCONCLUSIVE ACCEPTED history preserves classifications', () => { const x=variableInput(1,3,{decisionHistory:[{sequence:1,decisionId:'D1',classification:'BLOCKED',evidenceRefs:['r1']},{sequence:2,decisionId:'D2',classification:'INCONCLUSIVE',evidenceRefs:['r2']},{sequence:3,decisionId:'D3',classification:'ACCEPTED',evidenceRefs:['r3']}]}); const out=renderDocumentationProjection(x); const d=out.documents['docs/DECISIONS.md'].content; assert.match(d,/BLOCKED/); assert.match(d,/INCONCLUSIVE/); assert.match(d,/ACCEPTED/); });
test('deterministic post-ledger overlay preserves accepted truth and retains blocked facts as history only', () => { const x=variableInput(1,51,{postLedgerFacts:[{factKey:'accepted-source',classification:'ACCEPTED',decisionId:'D-A',value:{publicationId:'OVERLAY-SOURCE'},evidenceRefs:['e-a'],mirroredThroughSequence:51},{factKey:'blocked-repair',classification:'BLOCKED',decisionId:'D-B',statement:{status:'blocked'},evidenceRefs:['e-b'],mirroredThroughSequence:51,overlayNotYetMirroredIntoEventLedger:true}]}); const out=renderDocumentationProjection(x); assert.match(out.documents['docs/CURRENT_STATE.md'].content,/OVERLAY-SOURCE/); assert.match(out.documents['docs/PROJECT_HISTORY.md'].content,/blocked-repair/); });
test('canonical 1-51 decision rendering emits every Architect decision at its real event sequence', () => { const out=renderDocumentationProjection(variableInput()); const d=out.documents['docs/DECISIONS.md'].content; for(const n of [1,5,8,11,15,18,21,24,27,30,34,37,41,44,47,50]) assert.match(d,new RegExp(`Sequence ${n}:`)); });
test('canonical decisions never render Sequence 0 and post-ledger facts never fabricate canonical sequence', () => { const x=variableInput(1,51,{postLedgerFacts:[{factKey:'ORCH-000078',classification:'BLOCKED',decisionId:'D',statement:{status:'blocked'},evidenceRefs:['e']} ]}); const d=renderDocumentationProjection(x).documents['docs/DECISIONS.md'].content; assert.equal(d.includes('Sequence 0'),false); assert.match(d,/Post-ledger ORCH-000078/); });
test('CURRENT_STATE satisfies the ORCH-000077/078/079 and live-host semantic contract', () => { const x=variableInput(1,51,{postLedgerFacts:[{factKey:'ORCH-000078',classification:'BLOCKED',decisionId:'D78',statement:{status:'BLOCKED'},evidenceRefs:['e78']},{factKey:'ORCH-000079',classification:'ACCEPTED',decisionId:'D79',value:{messageId:'ORCH-000079'},evidenceRefs:['e79']}]}); const d=renderDocumentationProjection(x).documents['docs/CURRENT_STATE.md'].content; for(const s of ['ORCH-000077','ORCH-000078','ORCH-000079','NOT SUCCEEDED','PROTECTED/SEPARATE','726/0/0']) assert.match(d,new RegExp(s.replace('/','\\/'))); });
test('BUGS_AND_LESSONS preserves required defect, repair, retry, lineage, immutability, and range lessons', () => { const x=variableInput(1,51,{semanticProfile:{...variableInput().semanticProfile,lessons:['SOURCE_ACCEPTED identity collision repair','stored-record self-hash repair','no-blind-retry / read-only reconciliation first','ORCH-000076 stale-lineage selection defect; ORCH-000077 lineage-first repair','ORCH-000076 terminal evidence immutability violation; use immutable amendment','ORCH-000078 fixed-final-sequence renderer defect; ORCH-000079 variable-range repair']}}); const d=renderDocumentationProjection(x).documents['docs/BUGS_AND_LESSONS.md'].content; for(const s of ['identity collision','self-hash','no-blind-retry','stale-lineage','immutability','variable-range']) assert.match(d,new RegExp(s)); });
test('ARCHITECTURE preserves variable-range, overlay, cursor-gate, host-governance, and AFFOTECH separation semantics', () => { const x=variableInput(1,51,{semanticProfile:{...variableInput().semanticProfile,architecture:['variable coherent canonical ranges; no final sequence 15 hard-code','structured post-ledger overlay never rewrites history','cursor advances only after docs preservation/readback and Architect acceptance','persistent host: current-lineage, PRE_DISPATCH_ELIGIBLE, target/registration, mutation lease, exactly-once, no blind retry, control precedence, no assistant-response-text authority','AFFOTECH remains separate/protected']}}); const d=renderDocumentationProjection(x).documents['docs/ARCHITECTURE.md'].content; for(const s of ['variable coherent','post-ledger','cursor advances','PRE_DISPATCH_ELIGIBLE','separate/protected']) assert.match(d,new RegExp(s)); });
test('BLOCKED and INCONCLUSIVE facts never become current accepted truth while ORCH-000079 remains accepted', () => { const x=variableInput(1,51,{postLedgerFacts:[{factKey:'ORCH-000078',classification:'BLOCKED',decisionId:'D78',statement:{status:'BLOCKED'},evidenceRefs:['e78']},{factKey:'ORCH-000079',classification:'ACCEPTED',decisionId:'D79',value:{publicationId:'GH-PUB-079'},evidenceRefs:['e79']}]}); const out=renderDocumentationProjection(x); assert.match(out.documents['docs/CURRENT_STATE.md'].content,/GH-PUB-079/); assert.match(out.documents['docs/PROJECT_HISTORY.md'].content,/BLOCKED/); });
test('full five-document semantic profile renders deterministically and passes contract validation', () => { const a=renderDocumentationProjection(variableInput()),b=renderDocumentationProjection(variableInput()); assert.equal(a.valid,true); assert.equal(a.projectionDigest,b.projectionDigest); assert.deepEqual(a.documentPaths,DOCUMENTATION_TARGETS); });
test('missing or ambiguous required semantic fact fails closed', () => { const x=variableInput(); delete x.semanticProfile; assert.equal(renderDocumentationProjection(x).reasonCodes[0],'REQUIRED_SEMANTIC_FACTS_MISSING'); });
const sixFactOverlay = () => [
  ['ORCH-000078','BLOCKED'],['ORCH-000079','ACCEPTED'],['ORCH-000080','BLOCKED'],['ORCH-000081','INCONCLUSIVE'],['ORCH-000082','INCONCLUSIVE'],['ORCH-000083','ACCEPTED']
].map(([factKey,classification])=>({factKey,classification,decisionId:`DECISION-${factKey}`,value:{messageId:factKey},evidenceRefs:[`evidence/${factKey}.json`],mirroredThroughSequence:51,overlayNotYetMirroredIntoEventLedger:true}));
test('variable-length six-fact overlay renders every fact with exact classifications', () => { const out=renderDocumentationProjection(variableInput(1,51,{postLedgerFacts:sixFactOverlay()})); assert.equal(out.valid,true); for(const [key,classification] of [['ORCH-000078','BLOCKED'],['ORCH-000079','ACCEPTED'],['ORCH-000080','BLOCKED'],['ORCH-000081','INCONCLUSIVE'],['ORCH-000082','INCONCLUSIVE'],['ORCH-000083','ACCEPTED']]) for(const d of Object.values(out.documents)) { assert.match(d.content,new RegExp(key)); assert.match(d.content,new RegExp(classification)); } });
test('six-fact overlay plus canonical decisions never emits Sequence 0', () => { const out=renderDocumentationProjection(variableInput(1,51,{postLedgerFacts:sixFactOverlay()})); const d=out.documents['docs/DECISIONS.md'].content; assert.equal(d.includes('Sequence 0'),false); for(const n of [1,5,8,11,15,18,21,24,27,30,34,37,41,44,47,50]) assert.match(d,new RegExp(`Sequence ${n}:`)); });
test('blocked and inconclusive overlays never replace accepted current source', () => { const out=renderDocumentationProjection(variableInput(1,51,{postLedgerFacts:sixFactOverlay()})); const current=out.documents['docs/CURRENT_STATE.md'].content; assert.match(current,/GH-PUB-077-PERSISTENT-HOST-LINEAGE-SELECTION-REPAIR-000001/); assert.doesNotMatch(current,/latest accepted source baseline: ORCH-000081/); });
test('exact six-fact profile renders all five documents deterministically', () => { const x=variableInput(1,51,{postLedgerFacts:sixFactOverlay()}),a=renderDocumentationProjection(x),b=renderDocumentationProjection(x); assert.equal(a.valid,true); assert.deepEqual(a.documents,b.documents); assert.equal(a.projectionDigest,b.projectionDigest); assert.deepEqual(a.documentPaths,DOCUMENTATION_TARGETS); });
test('project history explicitly preserves canonical milestone classifications and failed-before-send outcome', () => { const d=renderDocumentationProjection(variableInput(1,51,{postLedgerFacts:sixFactOverlay()})).documents['docs/PROJECT_HISTORY.md'].content; for(const s of ['ORCH-000068','INCONCLUSIVE','ORCH-000070','ORCH-000072','ORCH-000074','ORCH-000075','ORCH-000076','failed before send','ORCH-000077','lineage-first']) assert.match(d,new RegExp(s)); });
test('bugs and lessons preserves the ORCH-000076 to ORCH-000077 causal pair separately from immutability', () => { const d=renderDocumentationProjection(variableInput(1,51,{postLedgerFacts:sixFactOverlay()})).documents['docs/BUGS_AND_LESSONS.md'].content; assert.match(d,/ORCH-000076 stale-lineage selection defect/); assert.match(d,/ORCH-000077 accepted lineage-first selection repair/); assert.match(d,/ORCH-000076 immutable terminal evidence violation/); });
