import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { buildPublication, validatePointer, validateReceipt } from '../src/evidence/build-publication.js';
import { publishEvidence, writePointer } from '../src/evidence/publish-evidence.js';

const fixtureRoot = path.resolve('test/evidence-fixtures');
async function setup(role = 'executor') {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'orchestrator-evidence-'));
  await fs.mkdir(path.join(root, '.agent-work', 'reports', role), { recursive: true });
  await fs.mkdir(path.join(root, '.agent-work', 'outbox'), { recursive: true });
  await fs.copyFile(path.join(fixtureRoot, role === 'executor' ? 'executor-pass' : 'curator-blocked', 'report.md'), path.join(root, '.agent-work', 'reports', role, 'report.md'));
  await fs.copyFile(path.join(fixtureRoot, 'artifact', 'sample.txt'), path.join(root, '.agent-work', 'outbox', 'sample.txt'));
  const externalParent = await fs.mkdtemp(path.join(os.tmpdir(), 'orchestrator-drive-')); const drive = path.join(externalParent, 'My Drive'); const external = path.join(drive, 'AFFOTECH Supervisor Orchestrator Evidence'); await fs.mkdir(external, { recursive: true });
  return { root, drive, external, report: path.join(root, '.agent-work', 'reports', role, 'report.md'), artifact: path.join(root, '.agent-work', 'outbox', 'sample.txt') };
}
const inputFor = (env, role = 'executor') => ({ repositoryRoot: env.root, driveMyDriveRoot: env.drive, externalEvidenceRoot: env.external, reportPath: env.report, role, milestone: 'ORCH.P0.EVIDENCE.TEST', result: role === 'executor' ? 'PASS' : 'BLOCKED', artifacts: [env.artifact] });

test('Executor publication writes immutable report, artifact, receipt, and pointers', async () => { const env = await setup(); const beforeReport = await fs.readFile(env.report); const beforeArtifact = await fs.readFile(env.artifact); const result = await publishEvidence(inputFor(env)); assert.equal(result.classification, 'PUBLISHED'); assert.equal((await fs.readFile(path.join(env.external, result.reportRelativePath))).compare(beforeReport), 0); assert.equal((await fs.readFile(path.join(env.external, result.artifactRelativePaths[0]))).compare(beforeArtifact), 0); const receipt = JSON.parse(await fs.readFile(path.join(env.external, result.receiptRelativePath))); assert.equal(receipt.sourceReport.sha256, crypto.createHash('sha256').update(beforeReport).digest('hex')); assert.equal(receipt.artifacts[0].sha256, crypto.createHash('sha256').update(beforeArtifact).digest('hex')); assert.equal((await fs.readFile(env.report)).compare(beforeReport), 0); assert.equal((await fs.readFile(env.artifact)).compare(beforeArtifact), 0); });
test('Curator publication updates curator and milestone pointers', async () => { const env = await setup('curator'); const result = await publishEvidence(inputFor(env, 'curator')); assert.equal(result.classification, 'PUBLISHED'); assert.equal(result.pointerPaths.includes('current/LATEST_CURATOR_REPORT.json'), true); assert.equal(JSON.parse(await fs.readFile(path.join(env.external, 'current/LATEST_MILESTONE.json'))).role, 'curator'); });
test('publicationId is deterministic and repeat publication is ALREADY_PUBLISHED', async () => { const env = await setup(); const input = inputFor(env); const firstModel = await buildPublication(input); const secondModel = await buildPublication(input); assert.deepEqual(firstModel, secondModel); await publishEvidence(input); const repeated = await publishEvidence(input); assert.equal(repeated.classification, 'ALREADY_PUBLISHED'); assert.equal((await fs.readdir(path.join(env.external, 'receipts'))).length, 1); });
test('differing report collision fails closed', async () => { const env = await setup(); const input = inputFor(env); const model = await buildPublication(input); await publishEvidence(input); await fs.writeFile(path.join(env.external, model.report.externalRelativePath), 'tampered'); await assert.rejects(() => publishEvidence(input), /immutable collision/); });
test('differing artifact collision fails closed', async () => { const env = await setup(); const input = inputFor(env); const model = await buildPublication(input); await publishEvidence(input); await fs.writeFile(path.join(env.external, model.receipt.artifacts[0].externalRelativePath), 'tampered'); await assert.rejects(() => publishEvidence(input), /immutable collision/); });
test('report and artifact boundaries reject escape, mismatch, missing, and directory', async () => { const env = await setup(); await assert.rejects(() => buildPublication({ ...inputFor(env), reportPath: path.join(env.root, 'outside.md') })); await assert.rejects(() => buildPublication({ ...inputFor(env), role: 'curator' })); await assert.rejects(() => buildPublication({ ...inputFor(env), artifacts: [path.join(env.root, 'outside.bin')] })); await assert.rejects(() => buildPublication({ ...inputFor(env), reportPath: path.join(env.root, '.agent-work', 'reports', 'executor') })); });
test('external root binding rejects arbitrary expected-name root and accepts exact child', async () => { const env = await setup(); assert.equal((await buildPublication(inputFor(env))).externalEvidenceRoot, await fs.realpath(env.external)); for (const externalEvidenceRoot of [path.join(env.root, 'AFFOTECH Supervisor Orchestrator Evidence'), path.parse(env.root).root, path.join(env.drive, 'nested', 'AFFOTECH Supervisor Orchestrator Evidence'), path.join(env.root, 'affotech-system-v2-hybrid', 'AFFOTECH Supervisor Orchestrator Evidence')]) await assert.rejects(() => buildPublication({ ...inputFor(env), externalEvidenceRoot })); });
test('unexpected pointer owner fails closed', async () => { const env = await setup(); await fs.mkdir(path.join(env.external, 'current')); await fs.writeFile(path.join(env.external, 'current', 'LATEST_EXECUTOR_REPORT.json'), JSON.stringify({ evidenceProject: 'other' })); await assert.rejects(() => publishEvidence(inputFor(env)), /invalid existing current pointer/); });
test('apply-then-throw reconciles without retry', async () => { const env = await setup(); let writes = 0; const io = { writeFile: async (destination, bytes, options) => { writes++; await fs.writeFile(destination, bytes, options); if (writes === 1) throw Object.assign(new Error('ack lost'), { code: 'EIO' }); } }; const result = await publishEvidence(inputFor(env), { io }); assert.equal(result.classification, 'PUBLISHED'); assert.equal(writes >= 1, true); });
test('unresolved ambiguous write returns reconciliation required', async () => { const env = await setup(); const io = { writeFile: async () => { throw Object.assign(new Error('unknown'), { code: 'EIO' }); } }; await assert.rejects(() => publishEvidence(inputFor(env), { io }), /RECONCILIATION_REQUIRED/); });
test('pure model contains hashes and no generated identity', async () => { const env = await setup(); const model = await buildPublication(inputFor(env)); assert.equal(model.report.sha256, crypto.createHash('sha256').update(await fs.readFile(env.report)).digest('hex')); assert.equal(typeof model.publicationId, 'string'); assert.equal(model.publicationId.startsWith('PUB-'), true); });
test('parent symlink escapes are rejected for reports and artifacts', async () => { const env = await setup(); const outside = await fs.mkdtemp(path.join(os.tmpdir(), 'orchestrator-outside-')); const reportLink = path.join(env.root, '.agent-work', 'reports', 'executor', 'link'); const artifactLink = path.join(env.root, '.agent-work', 'outbox', 'link'); await fs.symlink(outside, reportLink, 'junction'); await fs.symlink(outside, artifactLink, 'junction'); await assert.rejects(() => buildPublication({ ...inputFor(env), reportPath: path.join(reportLink, 'evil.md') })); await assert.rejects(() => buildPublication({ ...inputFor(env), artifacts: [path.join(artifactLink, 'evil.bin')] })); });
test('incomplete, malformed, and role-mismatched pointers fail closed', async () => { const env = await setup(); await fs.mkdir(path.join(env.external, 'current')); for (const pointer of [{ evidenceProject: 'affotech-agent-orchestrator' }, { schemaVersion: '1.0', publicationId: 'PUB-x', evidenceProject: 'affotech-agent-orchestrator', role: 'executor', milestone: 'M', result: 'PASS', reportRelativePath: 'reports/executor/x', reportSha256: 'BAD', receiptRelativePath: 'receipts/x.json' }, { schemaVersion: '1.0', publicationId: 'PUB-x', evidenceProject: 'affotech-agent-orchestrator', role: 'curator', milestone: 'M', result: 'PASS', reportRelativePath: 'reports/curator/x', reportSha256: 'a'.repeat(64), receiptRelativePath: 'receipts/x.json' }]) { await fs.writeFile(path.join(env.external, 'current', 'LATEST_EXECUTOR_REPORT.json'), JSON.stringify(pointer)); await assert.rejects(() => publishEvidence(inputFor(env)), /invalid existing current pointer/); } });
test('pointer apply-then-throw reconciles without retry', async () => { const env = await setup(); let renameCount = 0; const io = { rename: async (from, to) => { await fs.rename(from, to); renameCount++; if (renameCount === 1) throw Object.assign(new Error('ack lost'), { code: 'EIO' }); } }; const result = await publishEvidence(inputFor(env), { io }); assert.equal(result.statuses.pointers[0], 'RECONCILED_PUBLISHED'); assert.equal(renameCount, 2); });
test('absent pointer failure is definite and unresolved ambiguity requires an unknown third state', async () => { const env = await setup(); const io = { rename: async () => { throw Object.assign(new Error('unknown'), { code: 'EIO' }); } }; await assert.rejects(() => publishEvidence(inputFor(env), { io }), /POINTER_WRITE_FAILED/); });
test('receipt validator accepts complete receipt and rejects historical incomplete shape', () => { assert.equal(validateReceipt({ evidenceProject: 'affotech-agent-orchestrator' }), false); assert.equal(validateReceipt({ schemaVersion: '1.0', publicationId: `PUB-${'a'.repeat(32)}`, evidenceProject: 'affotech-agent-orchestrator', role: 'executor', milestone: 'M', result: 'PASS', sourceReport: { externalRelativePath: 'reports/executor/x.md', sha256: 'a'.repeat(64), size: 1 }, artifacts: [], publicationStatus: 'PUBLISHED' }), true); });
test('relative traversal, backslashes, cross-publication, and receipt mismatch paths are rejected', async () => { const env = await setup(); const model = await buildPublication(inputFor(env)); assert.equal(validatePointer({ ...model.pointers.role.model, reportRelativePath: 'reports/executor/../curator/evil.md' }, 'executor'), false); assert.equal(validatePointer({ ...model.pointers.role.model, reportRelativePath: 'reports/executor\\evil.md' }, 'executor'), false); assert.equal(validatePointer({ ...model.pointers.role.model, receiptRelativePath: 'receipts/../evil.json' }, 'executor'), false); assert.equal(validatePointer({ ...model.pointers.role.model, receiptRelativePath: 'receipts/PUB-deadbeefdeadbeefdeadbeefdeadbeef.json' }, 'executor'), false); assert.equal(validateReceipt({ ...model.receipt, sourceReport: { ...model.receipt.sourceReport, externalRelativePath: 'reports/executor/../evil.md' } }), false); assert.equal(validateReceipt({ ...model.receipt, artifacts: [{ ...model.receipt.artifacts[0], externalRelativePath: `artifacts/${model.publicationId}/../other/file` }] }), false); assert.equal(validateReceipt({ ...model.receipt, artifacts: [{ ...model.receipt.artifacts[0], externalRelativePath: `artifacts/PUB-${'b'.repeat(32)}/sample.txt` }] }), false); });
test('valid bridge publication IDs and exact pointer paths are accepted', async () => { const env = await setup(); const model = await buildPublication(inputFor(env)); assert.match(model.publicationId, /^PUB-[0-9a-f]{32}$/); assert.equal(validatePointer(model.pointers.role.model, 'executor'), true); assert.equal(validateReceipt(model.receipt), true); });
test('pointer failure before apply with existing destination is definite and does not retry', async () => { const env = await setup(); const old = await buildPublication(inputFor(env)); const newer = await buildPublication({ ...inputFor(env), milestone: 'ORCH.NEW' }); const destination = path.join(env.external, 'current', 'LATEST_EXECUTOR_REPORT.json'); await fs.mkdir(path.dirname(destination), { recursive: true }); const oldBytes = Buffer.from(JSON.stringify(old.pointers.role.model) + '\n'); await fs.writeFile(destination, oldBytes); let renameCalls = 0; await assert.rejects(() => writePointer({ readFile: fs.readFile, writeFile: fs.writeFile, rename: async () => { renameCalls++; throw Object.assign(new Error('before apply'), { code: 'EIO' }); } }, destination, newer.pointers.role.model, 'executor'), /POINTER_WRITE_FAILED/); assert.equal(renameCalls, 1); assert.deepEqual(await fs.readFile(destination), oldBytes); });
test('pointer failure before apply with absent destination is definite', async () => { const env = await setup(); const model = await buildPublication(inputFor(env)); const destination = path.join(env.external, 'current', 'LATEST_EXECUTOR_REPORT.json'); await fs.mkdir(path.dirname(destination), { recursive: true }); await assert.rejects(() => writePointer({ readFile: fs.readFile, writeFile: fs.writeFile, rename: async () => { throw Object.assign(new Error('before apply'), { code: 'EIO' }); } }, destination, model.pointers.role.model, 'executor'), /POINTER_WRITE_FAILED/); });
test('pointer replacement changing destination to unknown bytes is reconciliation-required', async () => { const env = await setup(); const model = await buildPublication(inputFor(env)); const destination = path.join(env.external, 'current', 'LATEST_EXECUTOR_REPORT.json'); await fs.mkdir(path.dirname(destination), { recursive: true }); await assert.rejects(() => writePointer({ readFile: fs.readFile, writeFile: fs.writeFile, rename: async (_from, to) => { await fs.writeFile(to, 'unknown'); throw Object.assign(new Error('ack lost'), { code: 'EIO' }); } }, destination, model.pointers.role.model, 'executor'), /RECONCILIATION_REQUIRED/); });
test('Executor milestone pointer can transition to Curator and back to Executor', async () => { const env = await setup(); const executor = await publishEvidence(inputFor(env)); await fs.mkdir(path.join(env.root, '.agent-work', 'reports', 'curator'), { recursive: true }); const curatorReport = path.join(env.root, '.agent-work', 'reports', 'curator', 'report.md'); await fs.copyFile(path.join(fixtureRoot, 'curator-blocked', 'report.md'), curatorReport); const curator = await publishEvidence(inputFor({ ...env, report: curatorReport }, 'curator')); assert.equal(curator.classification, 'PUBLISHED'); const executorAgain = await publishEvidence({ ...inputFor(env), milestone: 'ORCH.EXECUTOR.AGAIN' }); assert.equal(executorAgain.classification, 'PUBLISHED'); assert.notEqual(executor.publicationId, curator.publicationId); });
test('role-specific pointers remain strict while generic milestone accepts either role', async () => { const env = await setup(); const executor = await publishEvidence(inputFor(env)); const executorPointer = JSON.parse(await fs.readFile(path.join(env.external, 'current', 'LATEST_EXECUTOR_REPORT.json'))); const curatorPointer = { ...executorPointer, role: 'curator', reportRelativePath: 'reports/curator/curator.md' }; assert.equal(validatePointer(executorPointer, { expectedRole: 'executor' }), true); assert.equal(validatePointer(curatorPointer, { expectedRole: 'curator' }), true); assert.equal(validatePointer(curatorPointer, { expectedRole: 'executor' }), false); assert.equal(validatePointer(curatorPointer, { allowedRoles: ['executor', 'curator'] }), true); });
test('invalid second pointer is caught by preflight before any current-pointer write', async () => { const env = await setup(); await publishEvidence(inputFor(env)); const milestonePath = path.join(env.external, 'current', 'LATEST_MILESTONE.json'); await fs.writeFile(milestonePath, JSON.stringify({ evidenceProject: 'affotech-agent-orchestrator' })); const writes = []; const io = { writeFile: async (destination, bytes, options) => { if (destination.includes(`${path.sep}current${path.sep}`)) writes.push(destination); return fs.writeFile(destination, bytes, options); } }; await assert.rejects(() => publishEvidence({ ...inputFor(env), milestone: 'ORCH.PREFLIGHT' }, { io }), /invalid existing current pointer/); assert.equal(writes.length, 0); });
test('first pointer applies and second apply-then-throw reconciles to complete', async () => { const env = await setup(); await publishEvidence(inputFor(env)); let renames = 0; const io = { rename: async (from, to) => { await fs.rename(from, to); renames++; if (renames === 2) throw Object.assign(new Error('ack lost'), { code: 'EIO' }); } }; const result = await publishEvidence({ ...inputFor(env), milestone: 'ORCH.SECOND.RECONCILED' }, { io }); assert.equal(result.statuses.pointers[1], 'RECONCILED_PUBLISHED'); assert.equal(renames, 2); });
test('first pointer applies and second unchanged failure is explicit partial with no rollback', async () => { const env = await setup(); await publishEvidence(inputFor(env)); const oldMilestone = await fs.readFile(path.join(env.external, 'current', 'LATEST_MILESTONE.json')); let renames = 0; const io = { rename: async (from, to) => { renames++; if (renames === 1) return fs.rename(from, to); throw Object.assign(new Error('before apply'), { code: 'EIO' }); } }; await assert.rejects(() => publishEvidence({ ...inputFor(env), milestone: 'ORCH.SECOND.PARTIAL' }, { io }), /POINTER_WRITE_FAILED.*appliedPointer/); assert.equal(renames, 2); assert.notDeepEqual(await fs.readFile(path.join(env.external, 'current', 'LATEST_EXECUTOR_REPORT.json')), oldMilestone); });
test('first pointer applies and second unknown state remains reconciliation-required without rollback', async () => { const env = await setup(); await publishEvidence(inputFor(env)); let renames = 0; const io = { rename: async (from, to) => { renames++; if (renames === 1) return fs.rename(from, to); await fs.writeFile(to, 'unknown-third-state'); throw Object.assign(new Error('unknown'), { code: 'EIO' }); } }; await assert.rejects(() => publishEvidence({ ...inputFor(env), milestone: 'ORCH.SECOND.UNKNOWN' }, { io }), /RECONCILIATION_REQUIRED.*appliedPointer/); assert.equal(renames, 2); });
