import test from 'node:test';
import assert from 'node:assert/strict';
import { createGitHubCuratorCursorStore } from '../src/curator/github-curator-cursor.js';
function client(){const s={};return {s,getBranchHead:async()=> 'r',readJsonAtRef:async p=>s[p]??null,readJsonCurrent:async p=>s[p]??null,createJson:async(p,r)=>{s[p]={record:r,blobSha:'a'.repeat(64)}},updateJsonCas:async(p,b,r)=>{s[p]={record:r,blobSha:'b'.repeat(64)}}};}
const make=(c=client())=>createGitHubCuratorCursorStore({repositoryFullName:'o/r',branch:'main',projectId:'p',client:c});
const req={targetEvent:{projectId:'p',sequence:1,eventId:'e1',eventPath:'evidence/events/e1.json',eventSha256:'a'.repeat(64)},documentationResultId:'r',documentationPreservationRef:'ref',architectDecisionId:'d',architectDecisionState:'ACCEPTED',updatedAt:1};
test('module import zero IO/timers/network',()=>assert.ok(make));
test('factory validates repository/branch/project/client',()=>assert.throws(()=>createGitHubCuratorCursorStore({}),/CONTRACT/));
test('ABSENT is valid pre-first-run cursor state',()=>assert.equal(make().validateCursor(null).absent,true));
test('malformed/foreign cursor fails closed',()=>assert.throws(()=>make().validateCursor({record:{pointerKind:'CURATOR_CURSOR',projectId:'q'}}),/CURSOR/));
test('advance requires exact canonical target event boundary',async()=>assert.equal((await make().advanceCursor(req)).status,'ADVANCED'));
test('advance requires completed documentationResultId',async()=>assert.equal((await make().advanceCursor({...req,documentationResultId:''})).status,'AMBIGUOUS'));
test('advance requires durable documentationPreservationRef',async()=>assert.equal((await make().advanceCursor({...req,documentationPreservationRef:''})).status,'AMBIGUOUS'));
test('advance requires ACCEPTED Architect decision bound to exact documentation result/preservation',async()=>assert.equal((await make().advanceCursor({...req,architectDecisionState:'PENDING'})).status,'AMBIGUOUS'));
test('proposed Curator cursor alone cannot advance',async()=>assert.equal((await make().advanceCursor({...req,architectDecisionId:''})).cursorAdvanceAuthorized,false));
test('cursor cannot advance on Executor PASS without Architect-accepted documentation result',async()=>assert.equal((await make().advanceCursor({...req,architectDecisionState:'PENDING'})).status,'AMBIGUOUS'));
test('cursor cannot skip an event gap',async()=>assert.equal((await make().advanceCursor({...req,targetEvent:{...req.targetEvent,sequence:3}})).status,'AMBIGUOUS'));
test('cursor cannot move backward',async()=>{const c=client();const s=make(c);await s.advanceCursor(req);const r=await s.advanceCursor({...req,targetEvent:{...req.targetEvent,sequence:0}});assert.equal(r.status,'AMBIGUOUS');});
test('exact idempotent replay allowed only with identical bindings',async()=>{const c=client();const s=make(c);await s.advanceCursor(req);assert.equal((await s.advanceCursor(req)).status,'ADVANCED');});
test('conflicting replay with changed docs/result/decision fails',async()=>{const c=client();const s=make(c);await s.advanceCursor(req);assert.equal((await s.advanceCursor({...req,documentationResultId:'other'})).status,'AMBIGUOUS');});
test('first advance uses conflict-safe create semantics',async()=>{const c=client();await make(c).advanceCursor(req);assert.ok(c.s['evidence/current/curator/CURATOR_CURSOR.json']);});
test('later advance uses observed blob CAS',async()=>{const c=client();const s=make(c);await s.advanceCursor(req);const r=await s.advanceCursor({...req,targetEvent:{...req.targetEvent,sequence:2,eventId:'e2'}});assert.equal(r.status,'ADVANCED');});
test('successful readback returns ADVANCED exact state',async()=>assert.equal((await make().advanceCursor(req)).status,'ADVANCED'));
test('stale CAS never overwrites/retries',async()=>{const c=client();const s=make(c);await s.advanceCursor(req);c.updateJsonCas=async()=>{throw Error('STALE')};assert.equal((await s.advanceCursor({...req,targetEvent:{...req.targetEvent,sequence:2,eventId:'e2'}})).status,'AMBIGUOUS');});
test('ambiguous advance returns AMBIGUOUS and reconciliation descriptor',async()=>{const c=client();c.createJson=async()=>{throw Error('UNKNOWN')};const r=await make(c).advanceCursor(req);assert.equal(r.status,'AMBIGUOUS');assert.ok(r.reconciliationDescriptor);});
test('reconciliation exact state => ADVANCED_RECONCILED',async()=>{const c=client();const s=make(c);await s.advanceCursor(req);assert.equal((await s.reconcileCursorAdvance(req)).status,'ADVANCED_RECONCILED');});
test('reconciliation distinguishes NOT_ADVANCED_SAFE/CONFLICT/INCONCLUSIVE',async()=>assert.equal((await make().reconcileCursorAdvance(req)).status,'NOT_ADVANCED_SAFE'));
test('cursor remains progress only and cannot accept source/docs or authorize workers',async()=>assert.equal((await make().advanceCursor(req)).mutationAuthorized,false));
test('sensitive assistant/chat/DOM/credential/private payload is rejected',async()=>assert.equal((await make().advanceCursor({...req,assistantText:'x'})).status,'AMBIGUOUS'));
test('no live docs/Drive/AFFOTECH/browser/lease/HumanAuth activity',async()=>{const r=await make().advanceCursor(req);assert.equal(r.retryAuthorized,false);});
