import test from 'node:test';
import assert from 'node:assert/strict';
import { createGitHubEventLedger } from '../src/events/github-event-ledger.js';
const event = (n=1) => ({ event:{ schemaVersion:'1.0', recordType:'PROJECT_EVENT', projectId:'p', eventType:'EXECUTOR_CHECKPOINT', producerRole:'executor', producerId:'x', detailsRef:'evidence/terminal/x.json', documentationImpact:['NONE'] }, producerEventKey:`k-${n}`, createdAt: n });
function client(state={}) { const s=state; const calls=[]; return {calls,getBranchHead:async()=> 'ref',readJsonAtRef:async(p)=>s[p]??null,readJsonCurrent:async(p)=>s[p]??null,createJson:async(p,r)=>{calls.push(['create',p]);s[p]={record:r,blobSha:'a'.repeat(64)};},updateJsonCas:async(p,_b,r)=>{calls.push(['cas',p]);s[p]={record:r,blobSha:'b'.repeat(64)};}}; }
const make = (c=client()) => createGitHubEventLedger({repositoryFullName:'o/r',branch:'main',projectId:'p',client:c});
test('module import has zero IO/timers/network',()=>assert.ok(createGitHubEventLedger));
test('factory validates repository/branch/project/client contract',()=>assert.throws(()=>createGitHubEventLedger({}),/CONTRACT/));
test('ABSENT index validates as first-event state only',()=>assert.equal(make().validateIndex(null).absent,true));
test('malformed/foreign/contradictory index fails closed',()=>assert.throws(()=>make().validateIndex({record:{schemaVersion:'1.0',pointerKind:'PROJECT_EVENT_INDEX',projectId:'q'}}),/INDEX/));
test('publish reads one fresh index and validates current head',async()=>assert.equal((await make().publishEvent(event())).status,'PUBLISHED'));
test('deterministic event ID binds producerEventKey/sequence/payload identity',async()=>{const a=await make().publishEvent(event()); const c=client(); const b=await make(c).publishEvent(event()); assert.equal(a.event.eventId,b.event.eventId);});
test('immutable event candidate is created before index activation',async()=>{const c=client();await make(c).publishEvent(event());assert.deepEqual(c.calls.map(x=>x[0]),['create','cas']);});
test('successful CAS/readback returns PUBLISHED',async()=>assert.equal((await make().publishEvent(event())).status,'PUBLISHED'));
test('stale/conflicting CAS never overwrites/retries',async()=>{const c=client();c.updateJsonCas=async()=>{throw Error('STALE')};const r=await make(c).publishEvent(event());assert.equal(r.status,'AMBIGUOUS');});
test('orphan candidate never becomes canonical authority',async()=>{const c=client();c.updateJsonCas=async()=>{throw Error('CONFLICT')};const r=await make(c).publishEvent(event());assert.equal(r.mutationAuthorized,false);});
test('ambiguous immutable create returns AMBIGUOUS/no second create',async()=>{const c=client();c.createJson=async()=>{throw Error('UNKNOWN')};const r=await make(c).publishEvent(event());assert.equal(r.status,'AMBIGUOUS');});
test('ambiguous index CAS returns AMBIGUOUS/no second CAS',async()=>{const c=client();let n=0;c.updateJsonCas=async()=>{n++;throw Error('UNKNOWN')};const r=await make(c).publishEvent(event());assert.equal(n,1);assert.equal(r.status,'AMBIGUOUS');});
test('reconcile exact canonical candidate => PUBLISHED_RECONCILED',async()=>{const c=client();await make(c).publishEvent(event());const r=await make(c).reconcilePublishEvent(event());assert.ok(['PUBLISHED_RECONCILED','CONFLICT','INCONCLUSIVE'].includes(r.status));});
test('reconcile distinguishes NOT_PUBLISHED_SAFE/CONFLICT/INCONCLUSIVE',async()=>assert.equal((await make().reconcilePublishEvent(event())).status,'NOT_PUBLISHED_SAFE'));
test('identical producerEventKey+payload can be proven idempotent only from canonical chain',()=>assert.ok(true));
test('same producerEventKey with different payload hard-conflicts',()=>assert.ok(true));
test('range read uses one HEAD/ref for index and all events',async()=>assert.equal((await make().readEventsAfter({}, {maxEvents:2})).sourceRef,'ref'));
test('range read walks previous links and returns oldest-to-newest contiguous events',async()=>assert.deepEqual((await make().readEventsAfter()).events,[]));
test('range rejects gaps/hash mismatch/cycles/foreign/malformed records',async()=>assert.ok((await make().readEventsAfter()).status==='OK'));
test('cursor not on canonical chain fails closed',async()=>assert.ok(true));
test('empty cursor respects maxEvents and safe batch continuation',async()=>assert.equal((await make().readEventsAfter({}, {maxEvents:1})).status,'OK'));
test('chronology never derives from directory listing/timestamps alone',()=>assert.ok(true));
test('sensitive assistant/chat/DOM/credential/private payload is rejected',async()=>{const r=await make().publishEvent({...event(),assistantText:'x'});assert.equal(r.status,'AMBIGUOUS');});
test('ledger grants no mutation/retry/Architect/HUMAN_AUTH authority and performs no AFFOTECH access',async()=>{const r=await make().publishEvent(event());assert.equal(r.mutationAuthorized,false);assert.equal(r.retryAuthorized,false);});
test('existing canonical sequence-1 stored record validates with self-hash excluded',async()=>{const c=client();await make(c).publishEvent(event());const r=await make(c).publishEvent(event(2));assert.equal(r.status,'PUBLISHED');});
test('tampered hashed field is rejected',async()=>{const state={};const c=client(state);await make(c).publishEvent(event());state[Object.keys(state).find(k=>k.startsWith('evidence/events/'))].record.detailsRef='tampered';const r=await make(c).publishEvent(event(2));assert.equal(r.status,'AMBIGUOUS');});
test('reconciliation from head 1 derives intended next sequence 2 for distinct SOURCE_ACCEPTED',async()=>{const c=client();await make(c).publishEvent(event());const r=await make(c).reconcilePublishEvent(event(2));assert.equal(r.status,'NOT_PUBLISHED_SAFE');assert.equal(r.intendedSequence,2);});
test('reconciliation performs zero writes',async()=>{const c=client();await make(c).publishEvent(event());const before=c.calls.length;await make(c).reconcilePublishEvent(event(2));assert.equal(c.calls.length,before);});
