export const ACTION_CLASSES = Object.freeze(['ARCHITECT_TRIGGER', 'WORKER_DISPATCH', 'EXTERNAL_MUTATION']);
export const INTENT_TYPE = 'INTENT';
export const RESULT_TYPE = 'RESULT';
export const RESULT_OUTCOMES = Object.freeze(['APPLIED', 'NOT_APPLIED']);
export const RECONCILIATION_OBSERVATIONS = Object.freeze(['APPLIED', 'NOT_APPLIED', 'UNKNOWN']);
export const RECOVERY_CLASSIFICATIONS = Object.freeze({
  RECOVERED_SAFE_TO_CONTINUE: 'RECOVERED_SAFE_TO_CONTINUE',
  RECOVERED_RESTART_WORKER: 'RECOVERED_RESTART_WORKER',
  RECONCILIATION_REQUIRED: 'RECONCILIATION_REQUIRED',
  CIRCUIT_OPEN: 'CIRCUIT_OPEN',
  PAUSED_BY_RONY: 'PAUSED_BY_RONY'
});
export const SIDE_EFFECT_CLASSIFICATIONS = Object.freeze({
  READY_TO_INTENT: 'READY_TO_INTENT',
  ALREADY_COMPLETED: 'ALREADY_COMPLETED',
  RECONCILIATION_REQUIRED: 'RECONCILIATION_REQUIRED',
  KNOWN_NOT_APPLIED: 'KNOWN_NOT_APPLIED',
  FAIL_CLOSED: 'FAIL_CLOSED',
  CIRCUIT_OPEN: 'CIRCUIT_OPEN',
  RECONCILED_APPLIED: 'RECONCILED_APPLIED',
  RECONCILED_NOT_APPLIED: 'RECONCILED_NOT_APPLIED'
});
export const LEASE_CLASSIFICATIONS = Object.freeze({
  ACTIVE: 'ACTIVE',
  WORKER_LIVENESS_UNKNOWN: 'WORKER_LIVENESS_UNKNOWN',
  FENCED_STALE_WORKER: 'FENCED_STALE_WORKER',
  FAIL_CLOSED: 'FAIL_CLOSED'
});
