export const TRIGGER_TEXT = 'verify & next';
export const TRIGGER_RESULT_STATES = Object.freeze([
  'SENT',
  'RECONCILED_SENT',
  'PROVEN_NOT_SENT',
  'RECONCILIATION_REQUIRED',
  'TRIGGER_REFUSED'
]);
export const TRIGGER_CLASSIFICATIONS = Object.freeze({
  ELIGIBLE: 'ELIGIBLE',
  SENT: 'SENT',
  DUPLICATE_SUPPRESSED: 'DUPLICATE_SUPPRESSED',
  PROVEN_NOT_SENT: 'PROVEN_NOT_SENT',
  RECONCILED_SENT: 'RECONCILED_SENT',
  RECONCILIATION_REQUIRED: 'RECONCILIATION_REQUIRED',
  TRIGGER_REFUSED: 'TRIGGER_REFUSED',
  FAIL_CLOSED: 'FAIL_CLOSED'
});
export const FORBIDDEN_RELAY_PORTS = Object.freeze([9222, 9223]);
export const ALLOWED_RELAY_PORTS = Object.freeze([9333]);
export const BLOCKING_CONTROLS = Object.freeze([
  'PAUSED_BY_RONY',
  'STOP',
  'ABORT_CURRENT_WORKER',
  'RECONCILIATION_REQUIRED',
  'CIRCUIT_OPEN'
]);
